let canvasW=400,canvasH=600;
let playerX,playerY,playerSpeed=5,playerRadius=14;
let bullets=[];
let enemies=[];
let particles=[];
let stars=[];
let score=0;
let gameOver=false;
let localFrame=0;
let prevSpace=false;
function setup(){createCanvas(canvasW,canvasH);playerX=canvasW/2;playerY=canvasH-40;for(let i=0;i<30;i++){let s={x:random(0,canvasW),y:random(0,canvasH),spd:random(1,2),size:random(1,3)};stars.push(s);}}
function draw(){localFrame++;background(0);noStroke();fill(255);for(let i=0;i<stars.length;i++){let s=stars[i];ellipse(s.x,s.y,s.size,s.size);s.y+=s.spd;if(s.y>canvasH){s.y=0;s.x=random(0,canvasW);s.spd=random(1,2);s.size=random(1,3);}}if(!gameOver){if(keyIsDown(LEFT_ARROW))playerX-=playerSpeed;if(keyIsDown(RIGHT_ARROW))playerX+=playerSpeed;playerX=constrain(playerX,playerRadius,canvasW-playerRadius);let spacePressed=keyIsDown(32);if(spacePressed&&!prevSpace){let multiShot=random()<0.1;if(multiShot){let count=5;let spread=30;for(let i=0;i<count;i++){let t=(i/(count-1))*2-1;let vx=t*(spread/100);bullets.push({x:playerX,y:playerY-playerRadius,r:4,vy:-8,vx:vx});}}else{bullets.push({x:playerX,y:playerY-playerRadius,r:4,vy:-8,vx:0});}}prevSpace=spacePressed;if(localFrame%60===0){let ex=random(12,canvasW-12);let hp=random()<0.05?2:1;enemies.push({x:ex,y:-12,r:12,vy:2,hp:hp});}for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=b.vx;b.y+=b.vy;if(b.y<-b.r||b.x<-50||b.x>canvasW+50)bullets.splice(i,1);}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];e.y+=e.vy;if(e.y-e.r>canvasH)enemies.splice(i,1);}for(let ei=enemies.length-1;ei>=0;ei--){let e=enemies[ei];for(let bi=bullets.length-1;bi>=0;bi--){let b=bullets[bi];let dx=b.x-e.x;let dy=b.y-e.y;let dist2=dx*dx+dy*dy;let radSum=b.r+e.r;if(dist2<=radSum*radSum){bullets.splice(bi,1);e.hp-=1;if(e.hp<=0){enemies.splice(ei,1);for(let p=0;p<5;p++){let ang=random(0,PI*2);let sp=random(0.5,2.5);particles.push({x:e.x,y:e.y,r:3,life:20,vx:cos(ang)*sp,vy:sin(ang)*sp});}score+=1;break;}else{for(let p=0;p<3;p++){let ang=random(0,PI*2);let sp=random(0.5,1.5);particles.push({x:e.x,y:e.y,r:2,life:12,vx:cos(ang)*sp,vy:sin(ang)*sp});}}}}for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx;p.y+=p.vy;p.life-=1;if(p.life<=0)particles.splice(i,1);}for(let i=enemies.length-1;i>=0;i--){let e=enemies[i];let dx=e.x-playerX;let dy=e.y-playerY;let d2=dx*dx+dy*dy;let pr=playerRadius+e.r;if(d2<=pr*pr){gameOver=true;break;}}}noStroke();fill(255,255,0);triangle(playerX,playerY-playerRadius,playerX-playerRadius,playerY+playerRadius,playerX+playerRadius,playerY+playerRadius);fill(255,255,0);for(let i=0;i<bullets.length;i++){let b=bullets[i];ellipse(b.x,b.y,b.r*2,b.r*2);}fill(128,0,128);for(let i=0;i<enemies.length;i++){let e=enemies[i];ellipse(e.x,e.y,e.r*2,e.r*2);if(e.hp>1){fill(255);textSize(12);textAlign(CENTER,CENTER);text(e.hp,e.x,e.y);fill(128,0,128);}}for(let i=0;i<particles.length;i++){let p=particles[i];let alpha=map(p.life,0,20,0,255);fill(255,150,0,alpha);ellipse(p.x,p.y,p.r*2,p.r*2);}fill(255);textSize(16);textAlign(LEFT,TOP);text('Score: '+score,8,8);if(gameOver){textSize(32);textAlign(CENTER,CENTER);fill(255,0,0);text('GAME OVER',canvasW/2,canvasH/2);} }
